vim.cmd('packadd rainbow-delimiters.nvim')
vim.cmd('packadd vim-unimpaired')
vim.cmd('packadd nvim-surround')
require('nvim-surround').setup()
vim.cmd('packadd which-key.nvim')
require('which-key').setup()
vim.cmd('packadd nvim-unception')
vim.cmd('packadd vim-wakatime')
vim.cmd('packadd editorconfig.nvim')
