on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/flake-checker-action@main"
        with:
          fail-mode: true
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/magic-nix-cache-action@main"
      - name: Flake check
        run: nix flake check --all-systems --no-build
      - name: Check nix formatting
        run: |
          git ls-files '*.nix' | xargs nix develop --command alejandra --check
      - name: Check lua formatting
        run: |
          git ls-files '*.lua' | xargs nix develop --command stylua --check
